before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X github.com/yuyicai/kubei/cmd/version.gitVersion={{.Version}}
    -X github.com/yuyicai/kubei/cmd/version.gitCommit={{.Commit}}
    -X github.com/yuyicai/kubei/cmd/version.buildDate={{.Date}}
    -X github.com/yuyicai/kubei/cmd/version.gitMajor={{.Major}}
    -X github.com/yuyicai/kubei/cmd/version.gitMinor={{.Minor}}
    -X github.com/yuyicai/kubei/cmd/version.gitURL={{.GitURL}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge'
    - 'yml$'
    - 'yaml$'
